# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

  workflow_call:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: string-upload
        uses: jarrettgaither/bootcampexercise2-composite-action@v2
        with:
          user-string: 'Howdy Man'

  job3:
    runs-on: ubuntu-latest
    needs: job2
    strategy:
      matrix:
        nums: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Download string
        uses: actions/download-artifact@v4
        with:
          name: my_string
      - name: printing
        shell: bash
        run: |
          value=`cat my_string.txt`
          echo "$value - ${{matrix.nums}}"
