# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo ${{secrets.MY_PASSWORD}}

  job2:
    runs-on: self-hosted
    steps:
      - shell: bash
        run: echo "Hello Partner" > my_string.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_string
          path: my_string.txt

  job3:
    runs-on: self-hosted
    needs: job2
    strategy:
      matrix:
        nums: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Download string
        uses: actions/download-artifact@v4
        with:
          name: my_string
      - name: printing
        shell: bash
        run: |
          value = 'cat my_string.txt'
          echo "$value - ${{matrix.nums}}"
